nodeLinker: node-modules

enableGlobalCache: true

enableScripts: false

packageExtensions:
  "app-builder-lib@*":
    peerDependenciesMeta:
      dmg-builder:
        optional: true
      electron-builder-squirrel-windows:
        optional: true
